#include "config.h"
#include "action/keycode.h"

const MKL27ZOutputPin mkl27zColumnPins[] = {62, 63, 64, 19, 18, 21, 20, 44, 43, 42, 41, 40, 39, 38, 45};
const MKL27ZInputPin mkl27zRowPins[] = {33, 35, 36, 37, 49};

const MapT mkl27zMap { 
  KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUALS, KEY_BACKSLASH, KEY_TILDE,
  KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LBRACE, KEY_RBRACE, KEY_BACKSPACE, KEY_NONE,
  KEY_CAPS_LOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_QUOTE, KEY_ENTER, KEY_ENTER, KEY_NONE,
  MOD(0x2), MOD(0x2), KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH, MOD(0x20), MOD(0x20), MOD(0x20),
  MOD(0x1), MOD(0x8), MOD(0x4), KEY_NONE, KEY_NONE, KEY_NONE, KEY_SPACE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, MOD(0x40), MOD(0x80), MOD(0x10), KEY_NONE,
};
